name: Go

on:
  push:
    branches: [ "main", "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o appinstall
    
    - name: Display structure of downloaded files
      run: ls -R
    - uses: actions/upload-artifact@v3
      with:
        name: appinstall
        path: ./appinstall
        
    - uses: actions/download-artifact@v3
      with:
        name: appinstall
    
